# Generated by Django 5.1 on 2024-08-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterChef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='chefs_photos')),
                ('specializations', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Master Chefs',
            },
        ),
    ]
