# Generated by Django 5.1 on 2024-08-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters_chefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='staff_photos')),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.PositiveSmallIntegerField()),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ('sort',),
            },
        ),
        migrations.DeleteModel(
            name='MasterChef',
        ),
    ]
