# Generated by Django 5.1 on 2024-08-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_available',
        ),
        migrations.AddField(
            model_name='service',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
