# Generated by Django 5.1 on 2024-08-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0002_remove_service_is_available_service_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(default=2, upload_to='menu_photos'),
            preserve_default=False,
        ),
    ]
