# Generated by Django 5.1 on 2024-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
