# Generated by Django 5.1 on 2024-08-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('working_hours', models.CharField(max_length=100)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.establishment')),
            ],
            options={
                'verbose_name_plural': 'Contact information',
            },
        ),
    ]
