# Generated by Django 5.1 on 2024-08-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Dishes'},
        ),
    ]
